"""Decision layer for the drones.

Two ML-ish pieces live here:

1. A shallow ``DecisionTreeClassifier`` that maps
   (wave_height, current, wave_period, weld_integrity) to a mission state in
   {NORMAL, CAUTION, ABORT}. It is trained on a synthetic labelled dataset
   generated by ``_synthesize`` so the app has zero external training artefacts.

2. The reliability function R(t) = exp(-lambda * t), where lambda is built
   from the same features. This gives us a smooth "health" curve for the KPI
   cards and is the pitch's mathematical hook.

Why a shallow decision tree?
  - Interpretable: ``feature_importances_`` is a ready-made pitch slide.
  - Deterministic and instantaneous inference (<1ms per call).
  - Learns back transparent domain thresholds, so jurors can spot-check it.
"""

from __future__ import annotations

from functools import lru_cache
from typing import Literal

import numpy as np
from sklearn.tree import DecisionTreeClassifier

State = Literal["NORMAL", "CAUTION", "ABORT"]
STATE_ORDER = ("NORMAL", "CAUTION", "ABORT")
FEATURE_NAMES = ("wave_height", "current_velocity", "wave_period", "weld_integrity")


# ---------------------------------------------------------------------------
# Reliability model:  R(t) = exp(-lambda * t)
# ---------------------------------------------------------------------------
#
# lambda is a per-tick failure rate assembled from three risk contributors.
# Coefficients are hand-tuned so that:
#   * calm sea + healthy weld  -> lambda ~ 0.02
#   * 3 m waves + weak weld    -> lambda ~ 0.20, R collapses fast -> ABORT
# Values are intentionally transparent so we can justify them to the jury.

LAMBDA_WAVE = 0.05          # per metre of significant wave height
LAMBDA_CURRENT = 0.03       # per m/s of ocean current
LAMBDA_WELD = 0.02          # per unit of (100 - weld_integrity)/100


def compute_lambda(
    wave_height: float,
    current_velocity: float,
    weld_integrity: float,
) -> float:
    """Failure-rate coefficient lambda from live telemetry."""

    weld_deficit = max(0.0, (100.0 - float(weld_integrity))) / 100.0
    return (
        LAMBDA_WAVE * float(wave_height)
        + LAMBDA_CURRENT * float(current_velocity)
        + LAMBDA_WELD * weld_deficit
    )


def reliability(lam: float, t_seconds: float) -> float:
    """R(t) = exp(-lambda * t). Clamped to [0, 1] for display."""

    r = float(np.exp(-lam * max(0.0, t_seconds)))
    return max(0.0, min(1.0, r))


# ---------------------------------------------------------------------------
# Synthetic training data for the classifier.
# ---------------------------------------------------------------------------
#
# We sample uniformly across realistic feature ranges and label each row with
# a transparent rule set. The decision tree learns those rules back. The
# labelling rules are kept here (not baked into the tree) so we can tweak the
# pitch narrative without retraining drama.

N_SYNTHETIC = 3000


def _label_row(wave: float, current: float, period: float, weld: float) -> State:
    """Domain-inspired label rules.

    ABORT when the sea is clearly unsafe OR the weld is compromised while
    conditions are already rough. CAUTION when any single metric is elevated.
    NORMAL otherwise.
    """

    if wave >= 3.0 or current >= 1.0 or weld < 40:
        return "ABORT"
    if wave >= 1.8 or current >= 0.6 or weld < 65 or period < 5.0:
        return "CAUTION"
    return "NORMAL"


def _synthesize(n: int = N_SYNTHETIC, seed: int = 42):
    rng = np.random.default_rng(seed)
    wave = rng.uniform(0.0, 6.0, n)
    current = rng.uniform(0.0, 3.0, n)
    period = rng.uniform(3.0, 14.0, n)
    weld = rng.uniform(0.0, 100.0, n)

    X = np.column_stack([wave, current, period, weld])
    y = np.array([_label_row(*row) for row in X])
    return X, y


class Classifier:
    """Thin wrapper over a fitted ``DecisionTreeClassifier``."""

    def __init__(self, model: DecisionTreeClassifier) -> None:
        self.model = model
        self.classes_: tuple[str, ...] = tuple(model.classes_)

    def predict(
        self,
        wave_height: float,
        current_velocity: float,
        wave_period: float,
        weld_integrity: float,
    ) -> State:
        x = np.array(
            [[wave_height, current_velocity, wave_period, weld_integrity]],
            dtype=float,
        )
        return str(self.model.predict(x)[0])  # type: ignore[return-value]

    def feature_importances(self) -> dict[str, float]:
        return dict(zip(FEATURE_NAMES, map(float, self.model.feature_importances_)))


@lru_cache(maxsize=1)
def get_classifier() -> Classifier:
    """Train once per process. Cached so Streamlit reruns don't retrain."""

    X, y = _synthesize()
    # Shallow tree: fast, interpretable, and enough to recover the rule set.
    model = DecisionTreeClassifier(max_depth=5, random_state=0)
    model.fit(X, y)
    return Classifier(model=model)


# ---------------------------------------------------------------------------
# Weld-integrity simulator
# ---------------------------------------------------------------------------
#
# The drone's "weld quality" isn't in the marine CSV, so we generate it as a
# random walk biased downward when the sea is rough. This feeds the classifier
# and lets weld quality slowly degrade during the demo even without hitting
# the disaster button.


def next_weld_integrity(
    previous: float,
    wave_height: float,
    rng: np.random.Generator | None = None,
) -> float:
    rng = rng or np.random.default_rng()
    drift = -0.4 * wave_height        # rougher sea -> weld degrades faster
    noise = rng.normal(0.0, 1.5)
    return float(np.clip(previous + drift + noise, 0.0, 100.0))
